### ISSUE TITLE
The Implementation of Functional Programming Languages

### ISSUE THREAD

**Issue by rljacobson** [orsinium-labs/rlci#5]
You would really enjoy the book [The Implementation of Functional Programming Languages](https://archive.org/details/implementationof00peyt/mode/2up) by Simon Peyton Jones. The author has [a digital version available for free on his website](https://www.microsoft.com/en-us/research/wp-content/uploads/1987/01/slpj-book-1987-small.pdf). It starts with lambda calculus and explains in detail how to write a Haskell-like programming language.

Best wishes!

**Comment by orsinium** [comment]
Thank you :)
